### ISSUE TITLE
Possible to have cur.fetchall() return a list of dicts (rather than tuples)?

### ISSUE THREAD

**Issue by warrencm** [ibrewster/p4d#14]
I'm fairly new to Python and have only recently started using P4D to interact with a compiled 4D application/database so I really appreciate the work that has gone into it and any guidance that might be provided on my question below.

My simplified/redacted code is as follows:

`import p4d`
`db = p4d.connect(None, "Username", "Password", "Address", "Port")`
`cur = db.cursor()`
`sql = "SELECT * FROM Person"`
`cur.execute(sql)`
`results = cur.fetchall()`

I note that cur.fetchall() returns a list of tuples based on my sql query. It seems a little cumbersome to have to reference the database columns represented in each tuple by their index. Is it possible to instead return a list of dicts so that the columns represented in each dict can be referenced by their key (which would presumably be the column name)?

Thanks again to all!

**Comment by ibrewster** [comment]
The logic is that this library conforms to the Python Database API Specification v2.0 (https://peps.python.org/pep-0249). In that specification, `fetchall()` (and the related `fetchmany()`) is specifically stated to return "a sequence of sequences (e.g. a list of tuples)" (see https://peps.python.org/pep-0249/#fetchall). 

Note that your question, however, is asked commonly enough to be referenced in the FAQ: https://peps.python.org/pep-0249/#frequently-asked-questions, which along with some explanation of the reasoning behind the specification, mentions that "there are several existing tools available which provide helpers for this task", though it doesn't actually reference any of them (probably because it would be a dynamically changing list). 

Admittedly, some DB drivers do provide "cursor factories" that can do what you ask, returning the results in various formats, however that is not part of the specification, and I never implemented such functionality for this driver.

One option that might be worth looking at, especially if you need to do a lot of data manipulation after retrieving the results, is pandas: https://pandas.pydata.org, though that may well be overkill for your needs (and comes with a learning curve!)

**Comment by warrencm** [comment]
@ibrewster thank you for your invaluable insights.

I had been using the code below in what I suspected to be a workaround but wasn't sure it was the most efficient method

`columns = [col[0].decode('ascii') for col in cur.description]`
`rows = [dict(zip(columns, row)) for row in cur.fetchall()]`

I'll take a closer look at pandas based on your suggestion also.

**Comment by ibrewster** [comment]
For what it's worth, that code looks fine to me (I'm not sure the 'ascii' is required as an argument for`decode` - I *think* you could just call `decode()` with no arguments, but that's minor), and if I *did* offer a "dict cursor" or the like that returned a list of dictionaries, I would probably do something quite similar.

Pandas is a great tool, well worth knowing if you are going to do heavy-duty number crunching in python (it can drastically speed up operations on large lists if used correctly) - thus the reason I suggested it. That said, if the above code works for you, just use it - nothing wrong with it! :-)
