### ISSUE TITLE
Segfault when retrieving "big" row

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#5]
I'm trying to read all data of more than 50 tables. It works for many but 12.

If I try one named "Heures" with 74 columns, a segfault occurs. If a limit my select to some columns (eg. 50 first ou 50 last) it works.

Digging into the fetchone method problem comes from lib4d_sql. I think there's a "buffer overflow" some where.

Can you give me some advice to debug lib4d_sql?

**Comment by olivier-monaco** [comment]
There seems to be more than one problem.

The root cause of this problem seems to come from the server. It send no result when the query is executed. I'm not able to go deeper.

But I've found a problem at https://github.com/ibrewster/p4d/blob/master/lib4d_sql/fourd.c#L178:
```c
	if(res->numRow > res->first_row+res->row_count_sent-1) { /*row out of local result_set but in serveur statement */
```

When numRow, first_row and row_count_sent are 0 we must go into the if but we are working with unsigned values, so we never go in...

My change:
```c
	if(res->numRow >= res->first_row+res->row_count_sent) { /*row out of local result_set but in serveur statement */
```

Now, no more segfault but no data are returned because of some "invalid" response from the server...

My workaround: limit my selects to 16 columns, use many selects to retrieve all columns of a row and merge returned data.

**Comment by ibrewster** [comment]
but numRow, if an unsigned value, *can't* be zero unless we have a rollover (which seems unlikely). The first line of that function is:

`res->numRow++;`

which means the only way numRow could be zero (since it is an unsigned int and therefore can't be -1) is if it started out at `UINT_MAX` and that, therefore, the `++` caused it to rollover. Frankly, if you have more than `UINT_MAX` rows to be fetched from the result, I think you have other issues than whether or not this code is 100% correct :-)

**Comment by olivier-monaco** [comment]
When fourd_next_row is called the first time, `res->numRow` is `UINT_MAX`. So the first row will have the number 0. And I juste have 171 000+ rows ;).

To go deeper on this issue, I think I needed to sniff network packets to understand what the server returned. And for some tables I also have strange "double free" error...

**Comment by ibrewster** [comment]
Ah, ok, I see that now. But look at the rest of the if statement: when row_count_sent and first_row are 0, then the if statement becomes:

`if(0>0+0-1)`

which of course evaluates to true. Since numRow can't be less than 1, that -1 means that we *do* hit that if block, even without a `>=`

So *that* code is fine. Now as far as the double free error, I think that's coming from here https://github.com/ibrewster/p4d/blob/master/p4d/p4d.py#L495 :

`self.lib4d_sql.free(strdata)`

It looks like sometimes the `ford_field_to_string` function either deallocated strata itself or never allocated it in the first place, leading to a double free. I *should* be able to check the return value of `ford_field_to_string`, I think.

Man I wish C has a "safe free", i.e. try to free it, but if it doesn't need freed, move on.

**Comment by olivier-monaco** [comment]
I'm okay with your first sentence, the if becomes:
```
if(0>0+0-1)
```

And no, it will not. We are working with unsigned numbers. I put a trace in the if block and no, it's not "true". Change it to
```
if (0+1>0+0)
```
and it works...

For the double free, I will check this.

**Comment by olivier-monaco** [comment]
Try this ;)
```c
#include <stdio.h>

int main() {
    unsigned int a = 0;
    unsigned int b = 0;
    unsigned int c = 0;
    if (a > b + c - 1) {
        printf("ibrewster is right.\n");
    } else if (a + 1 > b + c) {
        printf("olivier is right.\n");
    }
    return 0;
}
```

**Comment by ibrewster** [comment]
So I did some actual debugging on the code, and I see that you are right, with a caveat: while you are correct that we don't fetch a page of result in this function the first time through, it's because *we don't need to*. In fact, if we *did* fetch a page here when the numRow comes out to be zero, we'd be skipping over the first page of results!

How do I know this? Because the code works as-is. I've been using this code in production for *years* now, and while there may still be some issues, such as the double-free, and it doesn't handle bad data well, I have confirmed many times over that the code works.

In case you are wondering, I didn't write the C code. That came from the people at 4D. Thus my relative ignorance as far as what the code actually does or why it works :-)

**Comment by ibrewster** [comment]
All that said, I can easily create a segfault in any number of places by doing a `SELECT *` on pretty much any table I want. So there are issues, for sure. Just need to nail them down.

**Comment by ibrewster** [comment]
It does seem odd that it works without having to fetch more data from the server when row_count_sent is 0 though....

**Comment by olivier-monaco** [comment]
Let's try this.

I've modifier fetchone of py4d_cursor line 467 like this:
```python
        print('Num row {0}'.format(self.result.numRow))
        print('First row {0}'.format(self.result.first_row))
        print('Row count sent {0}'.format(self.result.row_count_sent))
        goodrow = self.lib4d_sql.fourd_next_row(self.result)
        if goodrow == 0:
            return None
```

Now I run:
```python
    with closing(cnx4d.cursor()) as cur:
        sql = 'SELECT * FROM Activites LIMIT 1'
        cur.execute(sql)
        row = cur.fetchone()
        print(row)

        sql = 'SELECT * FROM Heures LIMIT 1'
        cur.execute(sql)
        row = cur.fetchone()
        print(row)
```

The output:
```
Num row 4294967295
First row 0
Row count sent 1
(1, 1, 'Acompte', '', '', '', '', '', '', '', '', False, False, False, False, 0, False, '', 0, 0.0, 0.0)
Num row 4294967295
First row 0
Row count sent 0
Erreur de segmentation (core dumped)
```

So `numRow` is `UINT_MAX` before the first `fourd_next_row` call. The first table is a small table and the row is fetched when the query is executed. The second has 74 columns. No row was fetched.

**Comment by olivier-monaco** [comment]
Now, I changed the "if" in `fourd_next_row`. The output is:
```
Num row 4294967295
First row 0
Row count sent 1
(1, 1, 'Acompte', '', '', '', '', '', '', '', '', False, False, False, False, 0, False, '', 0, 0.0, 0.0)
Num row 4294967295
First row 0
Row count sent 0
None
```

But there are 171000+ rows in the Heures table!

**Comment by ibrewster** [comment]
Right. Therefore proving that you aren't getting something back from the server. Ok, getting a segfault is poor behavior, but you proved in the first test that the problem *isn't* in the four_next_row function, but rather in what you got back from the server.

I'm guessing the issue is a fixed-size buffer somewhere trying to store the row. When you have less than 15 or 20 columns, it's fine. When you have 74 columns, you get a buffer overflow, leading to the segfault you see.

When I first picked up the code there were a number of such fixed-length buffers resulting in longer queries being cut off. I fixed those, but it wouldn't surprise me in the least if there was something similar for data coming back that I've missed to-date.

**Comment by olivier-monaco** [comment]
I was previously using the PHP extension I faced many problems... Your corrected version is better but I think our data are... exotics...

So I dumped what socket_receiv_header read from the socket (https://github.com/ibrewster/p4d/blob/master/lib4d_sql/communication.c#L191). It must be header... it's data...

I think the previous call to socket_receiv_data did not read all data.

**Comment by ibrewster** [comment]
Quite possible. Can you compare the raw data (i.e. network packet sniff) with what socket_receiv_data is getting? That's how I caught the longer queries being cut off in the first place...

For what it's worth, this library came from the PHP extension in the first place. 4D had put a PHP wrapper around it, I put a python wrapper on it and fixed it up. To some extent. :-)

**Comment by olivier-monaco** [comment]
I got it!

I working with VERBOSE defined to 1.

I see a list of column types, from 1 to 74.
```
Column 1: VK_STRING (VK_STRING)   
Column 2: VK_LONG (VK_LONG)       
Column 3: VK_STRING (VK_STRING)   
Column 4: VK_STRING (VK_STRING)   
Column 5: VK_BOOLEAN (VK_BOOLEAN) 
Column 6: VK_TIME (VK_TIMESTAMP)  
...
Column 72: VK_STRING (VK_STRING)  
Column 73: VK_LONG (VK_LONG)       
Column 74: VK_LONG (VK_LONG)      
```

Then, it read the column names:
```
Column-Aliases-Base64 => '[NomPersonne] [IDSociete] ... [envoi_support_email] [e'
Alias 1: '[NomPersonne]'
...
Alias 53: '[envoi_support_email]' 
Alias 54: '[e'
```

We can see the Column-Aliases-Base64 is truncated!

**Comment by olivier-monaco** [comment]
Looks like this 2048 in:
```
		if(get(header,"Column-Aliases-Base64",column_alias,2048)==0) {
```

**Comment by ibrewster** [comment]
While that may well be an issue, I think the problem is actually a bit earlier than that line- looking at the header I get when selecting a large number of columns, the header itself is cut off, not just the base64 section. The cutoff just happens to occur partway through the base 64 section, so that is the section that appears truncated. Yeah, definitely looks like more fixed-size buffers to sniff out. That's one you pointed out there...

**Comment by olivier-monaco** [comment]
This is my problem:
```
#define MAX_HEADER_SIZE 2048
```

**Comment by olivier-monaco** [comment]
Pushing it to 4096 and it works!

**Comment by ibrewster** [comment]
Ah, yes, that would do it. I was looking at the code where the header was read in, and it looks for the end of the header properly, with no bounds. However, when it is *stored* in the result, it's stored into a char array of MAX_HEADER_SIZE, thus truncating the header. Makes sense.

I think I want to look at dynamically allocating that, rather than making it a fixed size.

**Comment by olivier-monaco** [comment]
Or maybe just a check to avoid going outside the buffer and generating an error. That is, for my "big" tables, something like 2500 seems enough. If you change it to 4096, I will never be an issue.

**Comment by ibrewster** [comment]
Well, we'd still generate an error, but it would be a known error, not a crash. Yes, I would agree that 4096 should never be an issue - but it's still a magic number, and I *hate* magic numbers. There should be no reason the system can't dynamically allocate the needed amount.

**Comment by olivier-monaco** [comment]
You need also to increase buffer size at https://github.com/ibrewster/p4d/blob/master/lib4d_sql/fourd_interne.c#L584 and some lines below.

**Comment by ibrewster** [comment]
Agreed

**Comment by olivier-monaco** [comment]
I found a table with 196 columns. I had to set `MAX_HEADER_SIZE` to 7100 and the buffer for column names to more than 5000... I may be right... dynamic allocation is needed.

**Comment by ibrewster** [comment]
With commit https://github.com/ibrewster/p4d/commit/727825260bff839dd7606c4707f29737a9820660, both places now dynamically allocate the amount of memory they need to store the data. This should resolve the buffer overflow issues with large headers, and fix any number of crash scenarios. Thanks to @olivier-monaco for helping track down the issue!

**Comment by olivier-monaco** [comment]
Great job... but you free some data too early : https://github.com/ibrewster/p4d/blob/master/lib4d_sql/fourd_interne.c#L629

strtok/strtok_s do it job into the first argument (here column_alias). You need to free column_alias when alias is no more needed (like line 646).

Anyway, this fix seems to also fix my "double free" problem. I have to fix some problem in my own code to fully check it.

**Comment by olivier-monaco** [comment]
And you did not change the "if" on https://github.com/ibrewster/p4d/blob/master/lib4d_sql/fourd.c#L181

Anyway, it's no more a problem because the main bug is fixed.

**Comment by ibrewster** [comment]
I didn't change the if because, as we discussed at length, *it is correct as-is* The problem was never that IF statement, it was the headers being cut off. Changing the IF statement would result in skipping the first result.

**Comment by ibrewster** [comment]
Yeah, I don't quite understand how strok works, or what it does. I was under the impression that once the command ran, I no longer needed the original. I'll move the free.
