### ISSUE TITLE
Why using a sub class of str for BLOB?

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#6]
Hi,

You are creating a sub-class of str called Binary for BLOB (and IMAGE) data. Using sub-class of str implies "decoding" but this is raw data. Why not using/sub-classing bytes?

**Comment by ibrewster** [comment]
Because it was written under python 2, where there was much less distinction between str and bytes, and everything came back as a str. It might be appropriate to re-work this at this time, but I'll have to think about what impact that might have.

**Comment by ibrewster** [comment]
Actually, in python 2 bytes is just an alias for str anyway, so at the time I wrote this it would have made no sense to use a bytes type. I'm not sure at what point that bytes alias was introduced, either, so using bytes could have been further problematic by breaking compatibility with "earlier" version of python2.

Under python 3 it would be somewhat more syntactically correct to use bytes, but I'm not sure there's enough of a point to it to break backwards compatibility at this time. Feel free to let me know if you disagree :)

**Comment by ibrewster** [comment]
That may be a possibility, or I could just say 2.6+ is good enough, dropping support for 2.5 and below. 2.6 is probably far enough back.

Regarding your issue, I suspect it *may* be due to not properly handling byte types as input - the code handles string, integer, date etc, but was never written to properly handle bytes, and as such could well handle them wrong. I haven't really done anything with BLOBs or images in my use of the adapter, so that portion of code is not well tested.

I'll try to take a look at it later today or tomorrow, and figure out what's going on there.

**Comment by ibrewster** [comment]
BTW, a result of "b'xxx'" is what you get if you call str() on a bytes object, so it's likely what is happening is that my code is just "converting" to a string (via the str call), rather than recognizing  byte data and treating it properly. Shouldn't be too big a deal to fix, but I'll have to do some testing to figure out exactly what I'm getting back from the DB.

**Comment by olivier-monaco** [comment]
Hi,

MySQL connector use a bytearray to represent binary data (BLOB). This allow to use the same type for Python 2 and Python 3. I think it can be a good choose to use it.

**Comment by ibrewster** [comment]
Changed subclass to type byte. Should still work back to 2.6 at least (as str), and seems more appropriate than bytearay, as we don't need a mutable type, and byte should work fairly seamlessly as a str replacement.

**Comment by ibrewster** [comment]
Just FYI, the PEP actually says that the Binary type should be a subclass of string:

https://www.python.org/dev/peps/pep-0249/#binary

That said, that was written pre-python3, and I do feel that under python3 bytes is a more appropriate type. Under 2, of course, bytes is just an alias for string, so by using the bytes type I remain PEP compliant under 2, and, I feel, true to the intent under 3.
