### ISSUE TITLE
Illegal UTF-16 surrogate

### ISSUE THREAD

**Issue by olivier-monaco** [ibrewster/p4d#7]
Hi,

When reading on field of one row over thousand, it raise the following exception:
```
  ...
  File ".../p4d/p4d/p4d.py", line 600, in __next__
    result = self.fetchone()
  File ".../p4d/p4d/p4d.py", line 505, in fetchone
    raise e
  File ".../p4d/p4d/p4d.py", line 502, in fetchone
    decoded_value = output.decode('UTF-16LE')
  File ".../venv3/lib/python3.5/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 86-87: illegal UTF-16 surrogate
```

The data to decode:
```
b'#\x002\x002\x001\x007\x001\x00 \x00C\x00h\x00e\x00c\x00k\x00 \x00J\x00S\x00 \x00P\x00H\x00P\x007\x00 \x00#\x002\x002\x001\x007\x001\x00 \x00C\x00h\x00e\x00c\x00k\x00 \x00J\x00S\x00 \x00P\x00H\x00P\x007\x00\r\x00 #\x8c\xd9\r\x00(\xf7\xa9\x0e\xc8\xd4H\x01'
``` 

The data as shown in 4D:
![image](https://user-images.githubusercontent.com/3101457/31653549-3d9a5ec8-b323-11e7-8d17-4281d4b474d7.png)

Data seems to be corrupted but do you have an idea to workaround this?

**Comment by ibrewster** [comment]
In p4d.py, line 502, you can add an errors="ignore" parameter which will do exactly what it says: ignore errors. The result when you do that with your string is something like:

`'#22171 Check JS PHP7 #22171 Check JS PHP7\r⌠\r\uf728\u0ea9퓈ň'`

So perhaps still less than ideal, but at least it would work. I think I'll ask the community what the default should be here, since I don't think the PEP addresses how to deal with bad data. Raising an error seems logical enough, but then there is no way to deal with said error, which isn't good, especially since it is an easy one to deal with. Not sure.

**Comment by ibrewster** [comment]
As I was unable to get any sort of feedback on standard methods of handling this (Perhaps there *is* no standard method, because most databases wouldn't allow the situation in the first place. Dunno), I just went ahead and implemented the "replace" option for dealing with decode errors. The characters it can't deal with will still be returned, but replaced with a valid character.
