### ISSUE TITLE
lib4d_sql gets stuck in an endless loop if offset is higher than row count

### ISSUE THREAD

**Issue by pingtux** [ibrewster/p4d#8]
Hi

When a higher offset than the total row count is specified, 4D server returns "Row-Count: <total_row_count>" and "Row-Count-Sent: <total_row_count>". Because of this, lib4d_sql expects data but the 4D server never sends a reply in this case. Therefore, lib4d_sql gets stuck in [frecv](https://github.com/ibrewster/p4d/blob/master/lib4d_sql/communication.c#L270). Do you have an idea how to prevent / mitigate this? I thought about implementing a timeout, but this is obviously not the best solution.

**Comment by ibrewster** [comment]
When you say "a higher offset ... is specified", are you referring to something in the SQL query itself, or some function you call? I'm not aware of a function where you specify an offset, so I'm guessing you are referring to a SQL query with an offset parameter, but I wanted to verify that I'm not missing something :-)

**Comment by pingtux** [comment]
Sorry, should have been clearer. I mean the offset in the SQL query, e.g. `SELECT * FROM table LIMIT 10 OFFSET 351` for a table that only has 350 records.

**Comment by ibrewster** [comment]
So after some debugging, it looks like the root cause of this issue lies in how 4D server responds. To use your numbers, If you say something like "OFFSET 345" in a table with 350 records, 4D server returns "Row-Count: 5" and "Row-Count-Sent: 5", which makes sense and of course works. However, in the case of an offset greater than the total row count available, 4D server returns the *total* row count in the table (350 in this example), rather than something sane like 0, which would properly short-circuit the for loop and avoid the issue. Since the server said we had 350 rows available, we then proceed to try to *read* those rows, run out of data (since there is no data to be had), and lock up waiting for it to arrive.

So that's the problem, the question then of course becomes how do we handle the situation (since we can't change what 4D sends us). I'm not seeing anything in the response that would indicate the issue directly, rather, I think the key here is in the first switch statement where the row status_code is read. When an invalid offset like this is requested, we get back an invalid status_code for the row, causing the switch statement to fall through to the default on line 289 of communication.c - which "prints" an error message and then blithely continues on to try to read the column information, which is where we get our hangup.

As such, I would propose that I need to change the default to behave similarly to a status_code of 2 (error reading data): that is, after printing the "Status code not supported" message, return 1 to indicate error. The only problem with this solution is that under this scenario the error_code and error_String members of the result are not set, so we should probably consider what proper values would be for these members and set those as well. I'll have to do some further digging to find out if there is some pattern to setting these values that I should adhere to, since they are typically set by the server.

**Comment by ibrewster** [comment]
I pushed a commit that should fix this issue, unless there is a situation where we get an invalid status_code for the row but still want to parse out the columns. I can't think of a situation where that would be the case (I would think that if there is good row data, we should get a good status code for the row), but I can't help but wonder if there was a reason the original authors of the library did things the way they did with the default *not* triggering an error exit...

**Comment by pingtux** [comment]
Thanks a lot for your troubleshooting and fixing. Sadly, the 4D server version I'm using (13.4.0) doesn't return an invalid `status_code` in case of an invalid offset (`status_code` 0 is returned). As far as I can tell from the client / server communication there's no way to differentiate queries with an invalid offset from queries with a valid one (in version 13.4.0).
I'm using the extension with a custom ORM (where all queries are constructed by the ORM) so I'll probably pass the limit to the extension every time it is set and throw an error if `Row-Count:` is higher than the limit (which should only occur when an invalid offset is specified). Not the cleanest solution, but should work.
